    s="Hello python"
    print(s.upper())
    print(s.lower())
    len(s)
    z="朝花夕拾"
    len(z)
    print(s[1])
    print(s[:4])
    print(s[-4:])
    print(z[:1])
    print(z[-2:])
    y="python的学习成果今天检测"
    print(y[-4:])
    print(y[:11])
    print(y[-4:,:11])
    q=(y[-4:])
    w=(y[:11])
    print(q+w)
    print("我叫{},正在学python".format("码小高"))
    print("至高无{}{}底捞针".format("上").format("海"))
     print("至高无{}{}底捞针".format("上","海"))
    print("{:<9}".format ("*****"))
    print("{:<9}".format ("*"))
    print("{:<9}".format ("*****"))
    print("{:<9}".format ("*"))
    print("{:<9}".format ("*****"))
    print("{:<9}".format ("*"))

    print("{:^5}".format ("静夜思"))
    print("{:>5}".format ("李白"))
    print("{:<5}".format ("床前明月光"))
    print("{:<5}".format ("疑是地上霜"))
    print("{:<5}".format ("举头望明月"))
    print("{:<5}".format ("低头思故乡"))
